baseURL = 'https://burystedmundsastronomy.org/'
languageCode = 'en-gb'
title = 'Bury St Edmunds Astronomy Association'
theme = 'bseastro'

[module]
    [[module.mounts]]
      source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
      target = "assets/js/bootstrap.bundle.min.js"
